/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FaviconDotpngRouteImport } from './routes/favicon[.]png'
import { Route as DashboardDotcssRouteImport } from './routes/dashboard[.]css'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiV1IndexRouteImport } from './routes/api/v1/index'
import { Route as VendorPhoenix_live_viewPhoenix_live_viewDotjsRouteImport } from './routes/vendor/phoenix_live_view/phoenix_live_view[.]js'
import { Route as VendorPhoenix_htmlPhoenix_htmlDotjsRouteImport } from './routes/vendor/phoenix_html/phoenix_html[.]js'
import { Route as VendorPhoenixPhoenixDotjsRouteImport } from './routes/vendor/phoenix/phoenix[.]js'
import { Route as ApiV1StateRouteImport } from './routes/api/v1/state'
import { Route as ApiV1RefreshRouteImport } from './routes/api/v1/refresh'
import { Route as ApiV1EventsRouteImport } from './routes/api/v1/events'
import { Route as ApiV1ControlRouteImport } from './routes/api/v1/control'
import { Route as ApiV1IssueIdentifierRouteImport } from './routes/api/v1/$issueIdentifier'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'

const FaviconDotpngRoute = FaviconDotpngRouteImport.update({
  id: '/favicon.png',
  path: '/favicon.png',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDotcssRoute = DashboardDotcssRouteImport.update({
  id: '/dashboard.css',
  path: '/dashboard.css',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1IndexRoute = ApiV1IndexRouteImport.update({
  id: '/api/v1/',
  path: '/api/v1/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorPhoenix_live_viewPhoenix_live_viewDotjsRoute =
  VendorPhoenix_live_viewPhoenix_live_viewDotjsRouteImport.update({
    id: '/vendor/phoenix_live_view/phoenix_live_view.js',
    path: '/vendor/phoenix_live_view/phoenix_live_view.js',
    getParentRoute: () => rootRouteImport,
  } as any)
const VendorPhoenix_htmlPhoenix_htmlDotjsRoute =
  VendorPhoenix_htmlPhoenix_htmlDotjsRouteImport.update({
    id: '/vendor/phoenix_html/phoenix_html.js',
    path: '/vendor/phoenix_html/phoenix_html.js',
    getParentRoute: () => rootRouteImport,
  } as any)
const VendorPhoenixPhoenixDotjsRoute =
  VendorPhoenixPhoenixDotjsRouteImport.update({
    id: '/vendor/phoenix/phoenix.js',
    path: '/vendor/phoenix/phoenix.js',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1StateRoute = ApiV1StateRouteImport.update({
  id: '/api/v1/state',
  path: '/api/v1/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RefreshRoute = ApiV1RefreshRouteImport.update({
  id: '/api/v1/refresh',
  path: '/api/v1/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EventsRoute = ApiV1EventsRouteImport.update({
  id: '/api/v1/events',
  path: '/api/v1/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ControlRoute = ApiV1ControlRouteImport.update({
  id: '/api/v1/control',
  path: '/api/v1/control',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1IssueIdentifierRoute = ApiV1IssueIdentifierRouteImport.update({
  id: '/api/v1/$issueIdentifier',
  path: '/api/v1/$issueIdentifier',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard.css': typeof DashboardDotcssRoute
  '/favicon.png': typeof FaviconDotpngRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/$issueIdentifier': typeof ApiV1IssueIdentifierRoute
  '/api/v1/control': typeof ApiV1ControlRoute
  '/api/v1/events': typeof ApiV1EventsRoute
  '/api/v1/refresh': typeof ApiV1RefreshRoute
  '/api/v1/state': typeof ApiV1StateRoute
  '/vendor/phoenix/phoenix.js': typeof VendorPhoenixPhoenixDotjsRoute
  '/vendor/phoenix_html/phoenix_html.js': typeof VendorPhoenix_htmlPhoenix_htmlDotjsRoute
  '/vendor/phoenix_live_view/phoenix_live_view.js': typeof VendorPhoenix_live_viewPhoenix_live_viewDotjsRoute
  '/api/v1/': typeof ApiV1IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard.css': typeof DashboardDotcssRoute
  '/favicon.png': typeof FaviconDotpngRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/$issueIdentifier': typeof ApiV1IssueIdentifierRoute
  '/api/v1/control': typeof ApiV1ControlRoute
  '/api/v1/events': typeof ApiV1EventsRoute
  '/api/v1/refresh': typeof ApiV1RefreshRoute
  '/api/v1/state': typeof ApiV1StateRoute
  '/vendor/phoenix/phoenix.js': typeof VendorPhoenixPhoenixDotjsRoute
  '/vendor/phoenix_html/phoenix_html.js': typeof VendorPhoenix_htmlPhoenix_htmlDotjsRoute
  '/vendor/phoenix_live_view/phoenix_live_view.js': typeof VendorPhoenix_live_viewPhoenix_live_viewDotjsRoute
  '/api/v1': typeof ApiV1IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard.css': typeof DashboardDotcssRoute
  '/favicon.png': typeof FaviconDotpngRoute
  '/api/v1/$': typeof ApiV1SplatRoute
  '/api/v1/$issueIdentifier': typeof ApiV1IssueIdentifierRoute
  '/api/v1/control': typeof ApiV1ControlRoute
  '/api/v1/events': typeof ApiV1EventsRoute
  '/api/v1/refresh': typeof ApiV1RefreshRoute
  '/api/v1/state': typeof ApiV1StateRoute
  '/vendor/phoenix/phoenix.js': typeof VendorPhoenixPhoenixDotjsRoute
  '/vendor/phoenix_html/phoenix_html.js': typeof VendorPhoenix_htmlPhoenix_htmlDotjsRoute
  '/vendor/phoenix_live_view/phoenix_live_view.js': typeof VendorPhoenix_live_viewPhoenix_live_viewDotjsRoute
  '/api/v1/': typeof ApiV1IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard.css'
    | '/favicon.png'
    | '/api/v1/$'
    | '/api/v1/$issueIdentifier'
    | '/api/v1/control'
    | '/api/v1/events'
    | '/api/v1/refresh'
    | '/api/v1/state'
    | '/vendor/phoenix/phoenix.js'
    | '/vendor/phoenix_html/phoenix_html.js'
    | '/vendor/phoenix_live_view/phoenix_live_view.js'
    | '/api/v1/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard.css'
    | '/favicon.png'
    | '/api/v1/$'
    | '/api/v1/$issueIdentifier'
    | '/api/v1/control'
    | '/api/v1/events'
    | '/api/v1/refresh'
    | '/api/v1/state'
    | '/vendor/phoenix/phoenix.js'
    | '/vendor/phoenix_html/phoenix_html.js'
    | '/vendor/phoenix_live_view/phoenix_live_view.js'
    | '/api/v1'
  id:
    | '__root__'
    | '/'
    | '/dashboard.css'
    | '/favicon.png'
    | '/api/v1/$'
    | '/api/v1/$issueIdentifier'
    | '/api/v1/control'
    | '/api/v1/events'
    | '/api/v1/refresh'
    | '/api/v1/state'
    | '/vendor/phoenix/phoenix.js'
    | '/vendor/phoenix_html/phoenix_html.js'
    | '/vendor/phoenix_live_view/phoenix_live_view.js'
    | '/api/v1/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardDotcssRoute: typeof DashboardDotcssRoute
  FaviconDotpngRoute: typeof FaviconDotpngRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
  ApiV1IssueIdentifierRoute: typeof ApiV1IssueIdentifierRoute
  ApiV1ControlRoute: typeof ApiV1ControlRoute
  ApiV1EventsRoute: typeof ApiV1EventsRoute
  ApiV1RefreshRoute: typeof ApiV1RefreshRoute
  ApiV1StateRoute: typeof ApiV1StateRoute
  VendorPhoenixPhoenixDotjsRoute: typeof VendorPhoenixPhoenixDotjsRoute
  VendorPhoenix_htmlPhoenix_htmlDotjsRoute: typeof VendorPhoenix_htmlPhoenix_htmlDotjsRoute
  VendorPhoenix_live_viewPhoenix_live_viewDotjsRoute: typeof VendorPhoenix_live_viewPhoenix_live_viewDotjsRoute
  ApiV1IndexRoute: typeof ApiV1IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/favicon.png': {
      id: '/favicon.png'
      path: '/favicon.png'
      fullPath: '/favicon.png'
      preLoaderRoute: typeof FaviconDotpngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard.css': {
      id: '/dashboard.css'
      path: '/dashboard.css'
      fullPath: '/dashboard.css'
      preLoaderRoute: typeof DashboardDotcssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/': {
      id: '/api/v1/'
      path: '/api/v1'
      fullPath: '/api/v1/'
      preLoaderRoute: typeof ApiV1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/phoenix_live_view/phoenix_live_view.js': {
      id: '/vendor/phoenix_live_view/phoenix_live_view.js'
      path: '/vendor/phoenix_live_view/phoenix_live_view.js'
      fullPath: '/vendor/phoenix_live_view/phoenix_live_view.js'
      preLoaderRoute: typeof VendorPhoenix_live_viewPhoenix_live_viewDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/phoenix_html/phoenix_html.js': {
      id: '/vendor/phoenix_html/phoenix_html.js'
      path: '/vendor/phoenix_html/phoenix_html.js'
      fullPath: '/vendor/phoenix_html/phoenix_html.js'
      preLoaderRoute: typeof VendorPhoenix_htmlPhoenix_htmlDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor/phoenix/phoenix.js': {
      id: '/vendor/phoenix/phoenix.js'
      path: '/vendor/phoenix/phoenix.js'
      fullPath: '/vendor/phoenix/phoenix.js'
      preLoaderRoute: typeof VendorPhoenixPhoenixDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/state': {
      id: '/api/v1/state'
      path: '/api/v1/state'
      fullPath: '/api/v1/state'
      preLoaderRoute: typeof ApiV1StateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/refresh': {
      id: '/api/v1/refresh'
      path: '/api/v1/refresh'
      fullPath: '/api/v1/refresh'
      preLoaderRoute: typeof ApiV1RefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/events': {
      id: '/api/v1/events'
      path: '/api/v1/events'
      fullPath: '/api/v1/events'
      preLoaderRoute: typeof ApiV1EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/control': {
      id: '/api/v1/control'
      path: '/api/v1/control'
      fullPath: '/api/v1/control'
      preLoaderRoute: typeof ApiV1ControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$issueIdentifier': {
      id: '/api/v1/$issueIdentifier'
      path: '/api/v1/$issueIdentifier'
      fullPath: '/api/v1/$issueIdentifier'
      preLoaderRoute: typeof ApiV1IssueIdentifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardDotcssRoute: DashboardDotcssRoute,
  FaviconDotpngRoute: FaviconDotpngRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
  ApiV1IssueIdentifierRoute: ApiV1IssueIdentifierRoute,
  ApiV1ControlRoute: ApiV1ControlRoute,
  ApiV1EventsRoute: ApiV1EventsRoute,
  ApiV1RefreshRoute: ApiV1RefreshRoute,
  ApiV1StateRoute: ApiV1StateRoute,
  VendorPhoenixPhoenixDotjsRoute: VendorPhoenixPhoenixDotjsRoute,
  VendorPhoenix_htmlPhoenix_htmlDotjsRoute:
    VendorPhoenix_htmlPhoenix_htmlDotjsRoute,
  VendorPhoenix_live_viewPhoenix_live_viewDotjsRoute:
    VendorPhoenix_live_viewPhoenix_live_viewDotjsRoute,
  ApiV1IndexRoute: ApiV1IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
